<?php

declare(strict_types=1);

namespace Waffle\Commons\Data\Warmup;

use InvalidArgumentException;
use Waffle\Commons\Contracts\Data\Query\QueryInterface;
use Waffle\Commons\Contracts\Data\Warmup\DataWarmerInterface;
use Waffle\Commons\Data\Compiler\SQLCompiler;
use Waffle\Commons\Data\Exception\WarmupException;

// NOTE: the filesystem / OPcache helpers (file_put_contents, rename, unlink,
// is_file, function_exists, ini_get, opcache_compile_file) are deliberately
// NOT imported: unqualified calls resolve through the namespace first, which
// lets the test suite intercept them (php-mock) to cover the failure branches
// without touching the real filesystem.
use function count;
use function dirname;
use function filter_var;
use function is_dir;
use function mkdir;
use function sprintf;
use function var_export;

use const FILTER_VALIDATE_BOOL;

/**
 * Pre-compiles a registry of named SQR trees into a single `<?php return […]`
 * cache file and primes OPcache shared memory with it (Roadmap Beta-3 — "CLI
 * Route & Cache Warmup"). After a deploy, the first live request `require`s
 * pre-compiled, injection-safe SQL from shared memory instead of walking the
 * AST on the hot path.
 *
 * Stateless by construction: the query map is fixed at boot, every call
 * recompiles from scratch, and the cache file is replaced atomically
 * (write-to-temporary + rename), so a resident worker can never observe a
 * half-written artifact.
 */
final readonly class QueryWarmer implements DataWarmerInterface
{
    /**
     * @param array<non-empty-string, QueryInterface> $queries Named SQR trees to pre-compile.
     * @param SQLCompiler $compiler Dialect-bound compiler producing parameterised SQL.
     * @param non-empty-string $cacheFile Absolute path of the generated artifact file.
     */
    public function __construct(
        private array $queries,
        private SQLCompiler $compiler,
        private string $cacheFile,
    ) {}

    /**
     * @throws InvalidArgumentException When a registered query cannot be
     *                                  compiled (e.g. it carries no source table).
     * @throws WarmupException When the artifact cannot be persisted.
     */
    #[\Override]
    public function warmUp(): array
    {
        if ($this->queries === []) {
            return [];
        }

        $compiled = [];
        foreach ($this->queries as $name => $query) {
            $artifact = $this->compiler->compile($query);
            $compiled[$name] = ['sql' => $artifact->sql, 'parameters' => $artifact->parameters];
        }

        $this->persist($compiled);

        return [sprintf('%d compiled SQR tree(s) → %s', count($compiled), $this->cacheFile)];
    }

    /**
     * Atomically writes the compiled map, then primes OPcache when available.
     *
     * @param array<non-empty-string, array{sql: string, parameters: list<null|bool|float|int|string>}> $compiled
     *
     * @throws WarmupException When the cache directory or file cannot be written.
     */
    private function persist(array $compiled): void
    {
        $directory = dirname($this->cacheFile);
        if (!is_dir($directory) && !mkdir($directory, 0o775, true) && !is_dir($directory)) {
            throw new WarmupException(sprintf('Unable to create the warmup cache directory "%s".', $directory));
        }

        $payload =
            "<?php\n\ndeclare(strict_types=1);\n\n"
            . "// Generated by `waffle data:warmup` — do not edit by hand.\n"
            . 'return '
            . var_export($compiled, true)
            . ";\n";

        $temporary = $this->cacheFile . '.tmp';
        if (file_put_contents($temporary, $payload) === false) {
            throw new WarmupException(sprintf('Unable to write the warmup artifact "%s".', $temporary));
        }

        if (!rename($temporary, $this->cacheFile)) {
            if (is_file($temporary)) {
                unlink($temporary);
            }

            throw new WarmupException(sprintf('Unable to publish the warmup artifact "%s".', $this->cacheFile));
        }

        // Compile straight into OPcache shared memory so the first request after
        // a deploy reads the artifact without touching disk. Skipped silently
        // when OPcache is absent or disabled on the CLI — the file artifact
        // alone already serves its purpose.
        if (
            function_exists('opcache_compile_file') && filter_var(ini_get('opcache.enable_cli'), FILTER_VALIDATE_BOOL)
        ) {
            opcache_compile_file($this->cacheFile);
        }
    }
}
